# Generated by Django 5.2.9 on 2026-01-30 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='admin', max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('constituency_code', models.CharField(max_length=10, unique=True)),
                ('total_voters', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('election_type', models.CharField(choices=[('general', 'General Election'), ('state', 'State Assembly'), ('local', 'Local Body')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('blockchain_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party_name', models.CharField(max_length=200)),
                ('party_symbol', models.ImageField(blank=True, null=True, upload_to='party_symbols/')),
                ('manifesto', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.election')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('election', 'constituency', 'name')},
            },
        ),
        migrations.AddField(
            model_name='constituency',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='voting.state'),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='voter_faces/')),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('has_voted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='voting.constituency')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='voting.state')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoterVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('face', 'Face Recognition'), ('liveness', 'Liveness Detection'), ('duplicate', 'Duplicate Check')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='voting.voter')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.voter')),
            ],
            options={
                'ordering': ['-cast_at'],
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
